### PR TITLE
CFTO pages are now availiable to view from the hub page - meaning les…

### PR DESCRIPTION
**Pull request by rossbruniges**
…s chance for a ctfo related typo

### CODE REVIEW

**Comment by rossbruniges** [comment]
I tried to run `npm run test` but got the following error:

```
u@h:~/Work/fear-core-app (feature/include-cfto-urls) $ npm run test

> @ test /Users/rossbruniges/Work/fear-core-app
> echo "Error: no test specified"

Error: no test specified
```

**Comment by dreamzmaster** [comment]
@rossbruniges Try running $ gulp test-unit, should be fine.

**Comment by rossbruniges** [comment]
Thanks @dreamzmaster but there doesn't look to be a gulp file in the project?

**Comment by dreamzmaster** [comment]
Ohh Sorry.. just realised incorrect repo :)

**Pull request merged**
